url: http:/www.amandakrauss.com
baseurl: /my-site

# Site settings
title: Amanda Krauss
email: virangana2003@yahoo.com
description: "Lover of Great UX, Digital Strategist, Lapsed Classicist."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
# people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/risatrix
  - title: github
    url: http://github.com/risatrix

# Postal address (add as many lines as necessary)
# address:
  # - line: 3481 Melrose Place
  # - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty


kramdown:
  parse_block_html: true
